# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: school_service.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14school_service.proto\x12\x0eschool_service\"6\n\x10GetSchoolRequest\x12\x10\n\x08username\x18\x01 \x01(\t\x12\x10\n\x08password\x18\x02 \x01(\t\"\x83\x01\n\x11GetSchoolResponse\x12\x14\n\x0c\x61\x63\x63\x65ss_token\x18\x01 \x01(\t\x12\x15\n\rrefresh_token\x18\x02 \x01(\t\x12\x15\n\rsession_state\x18\x03 \x01(\t\x12\x12\n\nexpires_in\x18\x04 \x01(\x05\x12\x16\n\x0eschool_user_id\x18\x05 \x01(\t2i\n\rSchoolService\x12X\n\x0fget_school_info\x12 .school_service.GetSchoolRequest\x1a!.school_service.GetSchoolResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'school_service_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_GETSCHOOLREQUEST']._serialized_start=40
  _globals['_GETSCHOOLREQUEST']._serialized_end=94
  _globals['_GETSCHOOLRESPONSE']._serialized_start=97
  _globals['_GETSCHOOLRESPONSE']._serialized_end=228
  _globals['_SCHOOLSERVICE']._serialized_start=230
  _globals['_SCHOOLSERVICE']._serialized_end=335
# @@protoc_insertion_point(module_scope)
